### ISSUE TITLE
[slots.js] WinMultiplier Changes

### ISSUE THREAD

**Issue by AbnerSquared** [kety-folf/discord-bot-js#8]
**Suggestion**:
Change the win multiplier used for slots from:
`Math.floor(Math.random()*10)` => `Math.floor(Math.random()* (10 - 2 + 1)) + 1`

**Reason**:
The win multiplier always has a chance to land at 0 or 1, which in turn causes winners to lose money, or get nothing back in the end. This change ensures that when they do end up winning, it's always going to be a positive return.

**Context**:
Random equation found from:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random

**Comment by kety-folf** [comment]
fixed
